name: Docker Build
on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches-ignore:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

      - name: Build Targets
        run: |
          ./make_targets.sh

      - name: Generate Configuration
        run: |
          ./generate_nginx_configuration.sh

      - name: Build Docker images
        run: |
          ./build_images.sh

      - name: Push Docker image
        run: |
          cd docker
          ./push_images.sh